### ISSUE TITLE
Decouple `Client` from `Operation`

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore.JVM#111]
I think it would be beneficial to reconsider the interface of `Operation` with respect to `Client`. Now it seems a bit implicitly coupled to the fact that a client contains an `ActorRef`. If we consider implementing the `ConnectionActor` in terms of Akka Streams then the current incarnation of `Client` on `Operation` seems awkward.

I am not sure what the best alternative is, perhaps removing client and use a client id if possible, or introduce some callback mechanism.

Rationale for this change is two-fold:

 - implement connection actor in terms of Akka Streams - Primary imminent goal.
 - separate non-akka related code into new module: `eventstore-client-core` that opens up for adding a more functional implementation using fs2 + cats-effect, `eventstore-client-fs2` - Distant goal.

WDYT @t3hnar

**Comment by t3hnar** [comment]
@ahjohannessen I can agree with this

**Comment by ahjohannessen** [comment]
Done in: 
https://github.com/EventStore/EventStore.JVM/commit/6bea0afff7fb2d051268ed18bc13846d00092a93

Closing issue.
