### ISSUE TITLE
"client not found for correlationId"?

### ISSUE THREAD

**Issue by evan108108** [EventStore/EventStore.JVM#120]
I have been getting this error a lot lately. When it happens I am unable to recover. Can anyone shed some light on why this might be happening and what I can do about it.

**Comment by t3hnar** [comment]
Hello @evan108108, 
how did you solve this?

**Comment by evan108108** [comment]
It was a logic issue on my end. Basically I was inadvertantly killing the actor and not restarting it properly. I closed the issue because I realized it was not a problem work the library.
