### ISSUE TITLE
"unhandled from message" errors when using projections

### ISSUE THREAD

**Issue by rickardoberg** [EventStore/EventStore.JVM#122]
OS: OSX
Server version: 5.0.0
Client version: 2.11-5.0.9

Given:
I'm importing events from a 3.9.4 ES instance, and writing to a single stream in an (initially empty) 5.0.0 ES instance that have projections setup for correlation-id, i.e. each unique id in metadata gets its own stream. In the same JVM I also have a subscriber using EsConnection.streamPublisher("mystreamname", new EventNumber.Exact( currentPosition ), true, null, false ) as the source, which updates a local read model database.

When:
When importing events and the correlation id projection is turned on the subscriber produces thousands of errors with this pattern:
ERROR eventstore.StreamSourceStage$$anon$1 - unhandled from message Actor[akka://MyApp/user/$a#1702033398]: StreamEventAppeared(IndexedEvent(EventRecord(Stream(mystreamname),EventNumber(36854),EventData(...)

If I instead import all the events but don't subscribe to the stream simultaneously, and instead subscribe after all events are imported, then there are no errors. If I turn off projections and subscribe at the same time there are no errors. It is only when I import events, with correlation id projection on, and subscribe during the import, that the errors occur.

In the error case the 5.0.0 ES starts empty, so when the subscribe happens to mystreamname it doesn't yet exist, it is created when the import starts. Is that a potential issue?

What does this error mean? Why does it occur? Is there anything I can do to prevent it?

**Comment by rickardoberg** [comment]
Ok, it seems what is happening is that for some reason more events are coming in than what can fit in the source buffer, and it then unsubscribes, and the errors are from the unsubscribed state not being able to handle the events that are coming in.

This is really bizarre. I thought the whole point of a reactive stream was that it did back pressure handling, so that the client buffer could not be overrun by too many events coming from the server. Why is the source, seemingly, asking for more events from the server than it can fit in its local buffer?

For reference, in SourceStreamLogic, this is the code that gets hit:
  def subscribed(): Unit = {

    def onEventAppeared(idxEvent: IndexedEvent): Unit = {
      enqueueAndPush(eventFrom(idxEvent))
      if (state.bufferFull) unsubscribe()
    }

    stageActorBecome {
      rcvEventAppeared(onEventAppeared) or
        rcvUnsubscribed(onUnsubscribeCompleted()) or
        rcvSubscribed(onSubscriptionCompleted)
    }
  }
---
state.bufferFull returns true. The size of the state buffer is the same as my "read-batch-size" setting.

**Comment by t3hnar** [comment]
@rickardoberg this is not expected behaviour, will you be able to create a pull request ?

**Comment by rickardoberg** [comment]
@t3hnar sorry, not following. A pull request for what? I've been able to find that there's a bug (seemingly) in the client, but I have no idea how to fix that. It's Scala, which I can barely read, and definitely not write. Or what are you asking for, precisely?

**Comment by t3hnar** [comment]
@rickardoberg I'm asking to fix a bug by writing scala code :)

**Comment by rickardoberg** [comment]
@t3hnar I absolutely hate Scala with a passion. I would rather die than try to fix this piece of shit. Sorry. 

So, if you won't fix it, then it seems my best option is to not use reactive streams at all, and go back to using connection.subscribeToStreamFrom, which seems to at least work.

If you're not going to fix this, please mark all of the reactive stream APIs as deprecated, completely, rather than keeping them in a broken state.

**Comment by ahjohannessen** [comment]
@rickardoberg You hating Scala is fine, by all means. Calling things shit and being disrespectful is not useful and productive. This is OSS and you are free to use something else.

@t3hnar I believe the buffer always tries to have `read-batch-size` in it, but never more than ` 2 * read-batch-size`. That might not be the right thing to do and I think it was done like that as an optimization of always trying to have data available for downstream.

**Comment by ahjohannessen** [comment]
>I've been able to find that there's a bug (seemingly) in the client

It would be useful to get steps to reproduce the bug or a failing test.

**Comment by ahjohannessen** [comment]
@bardurdam Do you have an idea of what might be wrong?

**Comment by rickardoberg** [comment]
@ahjohannessen be nice to people, but harsh on code, is a good rule of thumb. I appreciate the help from @t3hnar, but the client code for this is, clearly, shit. The PRIMARY purpose of a reactive client is to avoid back pressure issues, and now I'm finding back pressure issues. So it's badly designed, or badly done. I.e. I can't use it. So, I've already moved back to using the old API methods, that seem to be working properly. 

So I don't have failing tests or reproducable steps, because I've already given up on it. If the client can't handle the most basic thing like not overrunning an internal queue it's not a bug, it's just wrongly done. See what I mean?

**Comment by ahjohannessen** [comment]
> @ahjohannessen be nice to people, but harsh on code, is a good rule of thumb

Sure, nothing wrong with being harsh on code, but your attitude is clearly shit. If you pointed out faulty code, then it would be productive and helpful. However, when asked to help or provide some pointers to reproduce, you dismiss the whole thing as shit and move on. Odd thing to do, given that you probably use this in production for *free*. Not sure how that can be classified as being nice to people.

**Comment by ahjohannessen** [comment]
@rickardoberg This should be fixed in PR #123 - It was not a fatal error that you observed. It was that the JVM client had send backpressure to ES, while events were in flight from ES.
