### ISSUE TITLE
Failed to connect to Eventstore v20 through TCP with TLS enabled

### ISSUE THREAD

**Issue by miguelsantoszup** [EventStore/EventStore.JVM#253]
Hi!
Just to give a little bit of context, I'm trying to upgrade an application from use EventStore 5 to 20, and considering the route that would cost the least amount of effort, I'm just upgrading this lib from 5.x to version 7.4.0.
With EventStore 5, the application uses TCP without any security on it, but moving to Eventstore 20, we did configure TLS with some self-signed certificate to use over the TCP connection.
When trying to use the cluster configuration with gossip-seeds, we're running to the problem that the ClusterDIscoverActor hardcoded broadcasts the externalTcp address, even when the port is equal to 0.

I did a simple fix on this PR https://github.com/EventStore/EventStore.JVM/pull/252

If this code is not in within your standards, please consider developing some fix to this.
Or maybe there's another way to connect to the Leader node every time when using TCP with TLS enabled. If there's such a thing,
I'd be glad to hear it, because I'm really in the need of a solution to this, and kinda fast (the motivation is to upgrade our envirionment to contibue to be PCI-DSS compliant)

Thanks in advance!
Happy 2022 to all of you guys

**Comment by ahjohannessen** [comment]
@miguelsantoszup Is it possible for you to set this setting in ESDB20:

```
ExtTcpPort: 1113
AdvertiseTcpPortToClientAs: 1113
```
?

**Comment by ahjohannessen** [comment]
@miguelsantoszup I do not see any harm in merging your fix, though.

**Comment by miguelsantoszup** [comment]
@ahjohannessen the configuration `ExtTcpPort` and `EnableExternalTcp` was already in place.
Seems that `AdvertiseTcpPortToClientAs` configuration did the trick!
Resultant gossip:
> {
      ...
      "internalTcpIp": "eventstore-01.hostname.com",
      "internalTcpPort": 0,
      "internalSecureTcpPort": 1112,
      "externalTcpIp": "eventstore-01.hostname.com",
      "externalTcpPort": 1113,
      "externalSecureTcpPort": 1113,
      "httpEndPointIp": "eventstore-01.hostname.com",
      "httpEndPointPort": 2113,
      ...
    }

Thank you soooo much for the immediacy on your response and attention! Now I have not only one, but two solution for my problem. Amazing

**Comment by miguelsantoszup** [comment]
For those whom are facing the same problem, v8.0.1 fixes this issue as well.

**Comment by ahjohannessen** [comment]
>Seems that AdvertiseTcpPortToClientAs configuration did the trick!

Yep, I recall that was necessary for our cluster setup.

>Thank you soooo much for the immediacy on your response and attention! Now I have not only one, but two solution for my problem. Amazing

No problem 👍
