### ISSUE TITLE
CPU is at 10% even when the app is idle

### ISSUE THREAD

**Issue by gfduszynski** [EventStore/EventStore.JVM#30]
I use EventStore.JVM [2.0.0] with reference configuration and changed IP + port.
Establishing connection with ES 3.0.1 causes CPU usage to jump from 0.1% to 10%[i7 2xcore],
also it's eating up RAM at a rate of ~1 MB/s 
Logs show only heart beat messages going  in & out

Longer description:
EventStore is used with Akka Persistance (2.3.9) 
Problem was discovered after update to 2.0.0
I've tried 3 scenarios to separate source of the issue:
AKKA+ES.Persistance(1 actor, empty jurnal) -> CPU ~10% MEM ~130MB (~300MB after 2 minutes)
AKKA+LEVELDB ->  CPU ~0.2% MEM ~125MB const.
AKKA+LEVELDB+ESConnection(not used) -> CPU ~10% MEM ~130MB (~300MB after 2 minutes)

My conclusion is that the problem is related to established connection in EventStore.JVM. 
CPU goes down to 0.1% when i turn off the DB while the app is running.

**Comment by t3hnar** [comment]
Thanks @gfduszynski for reporting, I'll investigate.
Which OS/Java ?

**Comment by gfduszynski** [comment]
Windows 8.1 x64, Java 1.8.0.5

**Comment by gfduszynski** [comment]
We can do a hangout if you like, I could show you the issue live.

**Comment by gregoryyoung** [comment]
What are heartbeat timeouts set to? Just having heartbeats will cause some
action back and forth though it seems a bit high. Also does the memory
stabilize after time?

On Thursday, February 12, 2015, gfduszynski <notifications@github.com>
wrote:

> We can do a hangout if you like, I could show you the issue live.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.JVM/issues/30#issuecomment-74064833>
> .
>


-- 
Studying for the Turing test

**Comment by t3hnar** [comment]
I suppose it has something to do with Java 1.8, other configurations should work fine...
What is your -Xmx value ?

**Comment by gfduszynski** [comment]
interval = 500ms
timeout = 2s
Both default

**Comment by gfduszynski** [comment]
-Xmx isnt explicitly configured, I'll try to figure out the default

**Comment by gfduszynski** [comment]
Intellij SBT JVM options are set to:
- Max heap size 768 MB
- MaxPermSize 384 MB

**Comment by t3hnar** [comment]
Btw, there is a [CountAll](https://github.com/EventStore/EventStore.JVM/blob/master/src/main/scala/eventstore/examples/CountAll.scala) runnable class in sources, can you run and see whether you are experiencing the same issue?

**Comment by gfduszynski** [comment]
After 4 minutes i have 400 MB.
There is a pattern to the growth:
1,1,..,1,20 and so on.
Doesn't look like stopping, 
I'll leave it be for some time after the CountAll test.

**Comment by t3hnar** [comment]
can we have a hangout?

**Comment by gfduszynski** [comment]
With CountAll CPU is still around 10% but memory stabilizes around 60MB

**Comment by gfduszynski** [comment]
Yes, my email is <github login>@gmail.com

**Comment by t3hnar** [comment]
@gfduszynski could you send me those profile metrics or give permission to google drive folder ?

**Comment by gfduszynski** [comment]
Sure:
http://s000.tinyupload.com/index.php?file_id=45831585478357264565

**Comment by gfduszynski** [comment]
@gregoryyoung Memory usage doesn't stop growing until OutOfMemory

**Comment by t3hnar** [comment]
Looks like an akka issue, I'll keep this ticket open until it fixed in akka.
For now fix would be to force akka version to `2.3.6`

**Comment by t3hnar** [comment]
or add to your `application.conf`
`akka.io.tcp.windows-connection-abort-workaround-enabled = off`

**Comment by gfduszynski** [comment]
Thanks, this fixed the issue for me.
