### ISSUE TITLE
subscription actor & automatic reconnection

### ISSUE THREAD

**Issue by ubourdon** [EventStore/EventStore.JVM#33]
Hi.
When I use subscription actor, 
```
class EventListenner() extends Actor with ActorLogging {
	val connection = context.system.actorOf(ConnectionActor.props(), "connection")
	context.system.actorOf(SubscriptionActor.props(connection, self), "subscription"
	
override def preStart() = {
		log.info("ViewProcess actor started !")
		connection ! SubscribeTo(EventStream.All)  // TODO check reconnection
	}

	override def receive = {                // TODO stock last datetime event for each stream category & send it to database when actor stop
		case IndexedEvent(event, _) if(isTicketEvent(event) /*&& isNew(event)*/) => ???
		case _ => 
	}
	private def isTicketEvent(event: Event): Boolean = event.streamId.streamId.startsWith("ticket")
}
```
and GetEventstore shutdown & restart, the subscribe down at client side, and I don't know how to keep it up automatically. (I must restart my app actually) :/

Have you any tips ?
Thx for your response.

**Comment by t3hnar** [comment]
Which version of eventstore-client are you using ?

**Comment by ubourdon** [comment]
The last 2.0.2.

**Comment by t3hnar** [comment]
If server restarted within configured timeout, subscription should be recovered...
could you share client logs just before server started after shutdown ?

**Comment by t3hnar** [comment]
btw I see something strange in your example:
both
`context.system.actorOf(SubscriptionActor.props(connection, self), "subscription"`
and
`connection ! SubscribeTo(EventStream.All)`
will produce same events... please use single subscription mechanism at the same time.

**Comment by ubourdon** [comment]
Oh ok, thx for peer review :)
What is the best way ? first or second ?

**Comment by ubourdon** [comment]
When I use first one, I receive only `$` prefix tagged event and not my model event (which is in the past).
Normal ?

I receive also that : 
```Failure(eventstore.OperationTimeoutException: Operation hasn't got response from server for PackOut(ReadAllEvents(Position(1776291),500,Forward,false,true),ab5e2b21-e201-410a-a69b-e21bca9b18d9,Some(UserCredentials(admin,***))))```

**Comment by t3hnar** [comment]
**first case**: this will just subscribe to new events which will appear after subscription created.

**second case**: when you are using `catch-up subscription` - it reads events from provided position and then subscribe to new events which will appear 

> When I use first one, I receive only $ prefix tagged event and not my model event (which is in the past).
> Normal ?

Yes

> I receive also that : 
Failure(eventstore.OperationTimeoutException: Operation hasn't got response from server for > PackOut(ReadAllEvents(Position(1776291),500,Forward,false,true),ab5e2b21-e201-410a-a69b-e21bca9b18d9,Some(UserCredentials(admin,***))))

This is what I was talking about... you `eventstore.operation.timeout=7s`
https://github.com/EventStore/EventStore.JVM/blob/master/src/main/resources/reference.conf#L38

Please increase this value roughly to the time needed on server restart.

**Comment by ubourdon** [comment]
I use 

```
lazy val settings = Settings(
		address = new InetSocketAddress(url, port),
		defaultCredentials = (login |@| password) { (l,p) => UserCredentials(l,p) },
		operationTimeout = 20 seconds
	)
```

to increase operation timeout value, but i have the same issues after more time.
I test my code with another instance of geteventstore (in local way, with other data) and it work perfectly.
I think it is a server issue & not client issue.

**Comment by ubourdon** [comment]
Ok I try to move my data to local eventstore and it works.
I rebuild my distant eventore from scratch (i use docker) & it work perfectly.
So it was a weird issue probably with docker, i don't know.
Thx for helping & for your availability.

**Comment by t3hnar** [comment]
cool!
