### ISSUE TITLE
subscription actor & don't relisten old event

### ISSUE THREAD

**Issue by ubourdon** [EventStore/EventStore.JVM#34]
Hi,

Have you any tips, or geteventstore features, which allow to say to subscription actor to not be careful about Event it process before ?

Thx for your answer.

**Comment by t3hnar** [comment]
> not be careful about Event

Could you be more specific ? :)
maybe current and expected behaviour examples ?

**Comment by gregoryyoung** [comment]
I think he is looking for something that is not atleast-once messaging if
my guess is right

There isn't any way of doing this.

On Mon, Apr 20, 2015 at 8:32 PM, Yaroslav Klymko <notifications@github.com>
wrote:

> not be careful about Event
>
> Could you be more specific ? :)
> maybe current and expected behaviour examples ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.JVM/issues/34#issuecomment-94517453>
> .
>



-- 
Studying for the Turing test

**Comment by ubourdon** [comment]
Sorry, i'm not fluent in english.
I mean when I restart my app, my subscritpion actor catch all event, even the "past" event, event he yet process before.
I use subscription actor to increment the "Query part" (from CQRS) of my app, and if at each restart of my app, I must rebuild all my Views (because replaying all events), it is not very efficient.

**Comment by gregoryyoung** [comment]
One of the parameters of a catch up subscription is where to start eg you
can remember and pass the last event you processed when you come back up

On Mon, Apr 20, 2015 at 10:36 PM, @ugobourdon <notifications@github.com>
wrote:

> Sorry, i'm not fluent in english.
> I mean when I restart my app, my subscritpion actor catch all event, even
> the "past" event, event he yet process before.
> I use subscription actor to increment the "Query part" (from CQRS) of my
> app, and if at each restart of my app, I must rebuild all my Views (because
> replaying all events), it is not very efficient.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.JVM/issues/34#issuecomment-94549005>
> .
>



-- 
Studying for the Turing test

**Comment by ubourdon** [comment]
It mean for event i process, I must remember the last I process, isn't it ?

**Comment by t3hnar** [comment]
to not receive past events, you need to pass `SubscriptionActor.props(fromPositionExclusive = ...` taken from last processed event.
Or just rather not use catch-up subscription mechanism but directly `connection ! SubscribeTo(EventStream.All)`

**Comment by t3hnar** [comment]
@ubourdon is it still an issue?

**Comment by ubourdon** [comment]
No.
It's ok for me.
Thx for response.
