### ISSUE TITLE
spray dependencies

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore.JVM#36]
Hi :) 

Would it be possible to make the
```scala
  object Spray {
    val client = "io.spray" %% "spray-client" % "1.3.2"
    val json   = "io.spray" %% "spray-json" % "1.3.1"
  }
```
`provided` in order to avoid having unnecessary dependencies?

**Comment by ahjohannessen** [comment]
Ah, noticed that you use it for clustering.

**Comment by ahjohannessen** [comment]
Closing it.

**Comment by ahjohannessen** [comment]
@t3hnar wouldn't make sense use http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC4/scala/http/client-side/index.html instead of spray? :)

**Comment by ahjohannessen** [comment]
As far as I can tell, only ClusterInfo uses spray http. WDYT?

**Comment by t3hnar** [comment]
So I don't like dependency on spray, but there is nothing lightway in scala ecosystem for json/http.

What would you propose?

**Comment by t3hnar** [comment]
@ahjohannessen akka http is not an option, like many times slower then spray right now and still not released.

**Comment by ahjohannessen** [comment]
Perhaps http://dispatch.databinder.net/Dispatch.html is an option, seems to be a minimal library. Reason for asking this is because Akka 2.4 is around the corner and I do not know how well spray works with that. It might work just fine as they promise binary compatibility with 2.3. Just thought that it was quite a bit of libs to pull in.
There is also the client part of http4s, but I think that has a lot of baggage on various other libraries.

**Comment by ahjohannessen** [comment]
Here is another simple, no dependencies, http client. Found it via Google:
https://github.com/scalaj/scalaj-http

**Comment by t3hnar** [comment]
@ahjohannessen closing this one for now, will replace spray with `akka-http` when it gets more performant.

**Comment by ahjohannessen** [comment]
@t3hnar Could we reconsider this now Akka 2.4.2 is out with http?

**Comment by t3hnar** [comment]
@ahjohannessen yep, it does make sense now.

**Comment by ahjohannessen** [comment]
As far as I can tell, performance of akka http server side functionality is quite good according to https://groups.google.com/forum/#!topic/akka-user/XB7H2n2r-9A - I am not sure how well it fares with client side, but many things indicate that it should be fast

**Comment by ahjohannessen** [comment]
@t3hnar Is `https://gitter.im/EventStore/EventStore.Akka.Persistence` not active? I think it would be nice to have a `https://gitter.im/EventStore/EventStore.Akka.Persistence` and `https://gitter.im/EventStore/EventStore.JVM` as place to bounce off ideas and such :)

**Comment by t3hnar** [comment]
@ahjohannessen those are not active. I'd prefer to have all ideas in one place - http://groups.google.com/forum/#!forum/event-store

**Comment by ahjohannessen** [comment]
Yes, I can follow that point of view.

**Comment by t3hnar** [comment]
Fixed

**Comment by ahjohannessen** [comment]
:+1:
