### ISSUE TITLE
Including as dependency

### ISSUE THREAD

**Issue by revati** [EventStore/EventStore.JVM#37]
I can't find how i can add this project in my play framework build.sbt file to libraryDependencies.

Thanks for help

**Comment by t3hnar** [comment]
1. http://prntscr.com/7tv8e3
2. http://prntscr.com/7tv8nc 
3. http://prntscr.com/7tv8yo

**Comment by revati** [comment]
Thanks :)

**Comment by sthzg** [comment]
:+1: thanks for pointing out. in my opinion it would be great having the snippets for maven and sbt in the README as well. anyways, thanks for the project.
