### ISSUE TITLE
Create streams api for subscriptions with backpressure supported

### ISSUE THREAD

**Issue by t3hnar** [EventStore/EventStore.JVM#38]

**Comment by ahjohannessen** [comment]
Wuhuu :)

**Comment by gregoryyoung** [comment]
:+1:

**Comment by ahjohannessen** [comment]
That will make some things much simpler in our code, looking very much forward to it. Next step could be create a contrib project with adaptors for scalaz-stream `Process` in similar way Martin Krasser has in his streamz project :)

**Comment by ahjohannessen** [comment]
I am also looking forward to how Akka.Eventstore.Persistence will change when this lands in Akka:

https://github.com/akka/akka/compare/wip-16541-persistence-query

**Comment by t3hnar** [comment]
:)

**Comment by t3hnar** [comment]
released in `2.0.3`

**Comment by pawelkaczor** [comment]
:+1:
