### ISSUE TITLE
Subscribe to All Example

### ISSUE THREAD

**Issue by vornet** [EventStore/EventStore.JVM#39]
The "Subscribe to All" example uses an EsConnection and the implementation doesn't send messages like the other examples (read/write).  Is it possible to send messages to subscribe so that I can share the same connection, used in read/write?

I tried something like this, but it doesn't work:

{
        final ActorRef subscriptionObserver = _system.actorOf(Props.create(SubscriptionObserver.class));
        
        final SubscribeTo subscribeTo = new SubscribeToBuilder()  
        .toStream(stream)
        .build(); 
        
        _connection.tell(subscribeTo, subscriptionObserver);   
}

    public static class SubscriptionObserver extends UntypedActor {        
        public void onReceive(Object message) throws Exception {
				System.out.println("Got Message");
        }
    }

**Comment by t3hnar** [comment]
You should use:
```java
final EventStoreExtension extension = EventStoreExtension.get(system);
extension.actor();
extension.connection();
// both share same physical connection
```

In general `EsConnection.java` implemented via proxying messages to the actor.
