### ISSUE TITLE
build: reason for withSources

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore.JVM#40]
I noticed that the published jar has dependency on a series of sources. I believe it is recommended that one should use `updateClassifiers` in sbt in order to fetch sources and javadocs. 

Is it possible that you could remove `.map(_.withSources())` and publish a new version? Reason for asking is that I get a few of those sources while using sbt-native-packager to package my applications and I would rather not do manual filtering on `x-sources.jar` for that.

```scala
    libraryDependencies ++= Seq(
      Akka.actor, Akka.testkit, protobuf,
      typesafeConfig, codec, mockito,
      Joda.time, Joda.convert,
      Specs2.core, Specs2.mock,
      Spray.json, Spray.client,
      AkkaStream.stream, AkkaStream.tck, AkkaStream.testkit,
      ReactiveStreams.streams, ReactiveStreams.tck).map(_.withSources())
  )
```

**Comment by t3hnar** [comment]
@ahjohannessen my bad, will fix it, can you wait until akka 2.4 release or want it now?

**Comment by ahjohannessen** [comment]
I can wait, thanks Yaroslav :+1:

**Comment by ahjohannessen** [comment]
Btw, as a part of moving to 2.4 it would be nice if you also bumped to scala 2.11.7 :)

**Comment by t3hnar** [comment]
I cannot bump to `2.11.7`... there is a bug in compiler, however it works nice with `2.11.7` at runtime

**Comment by ahjohannessen** [comment]
I noticed that when I tried to compile it with 2.11.7, somehow it has issues compiling:
```scala
package eventstore

object SystemEventType {
  val streamDeleted = "$streamDeleted"
  val statsCollection = "$statsCollected"
  val linkTo = "$>"
  val metadata = "$metadata"
  val userCreated = "$UserCreated"
  val userUpdated = "$UserUpdated"
  val passwordChanged = "$PasswordChanged"
}
```
with `metadata` and `streamDeleted` being problematic.

**Comment by ahjohannessen** [comment]
I found a workaround:
```scala
  val streamDeleted = "$"+"streamDeleted"
  val metadata = "$"+"metadata"
```

**Comment by ahjohannessen** [comment]
If you leave xlint out it should work:
scalacOptions        := Seq("-encoding", "UTF-8", "-unchecked", "-deprecation", "-feature"/*, "-Xlint"*/)

**Comment by ahjohannessen** [comment]
Just to be complete, not that I think 2.11.7 is that important, just sharing my findings :) You can turn off the “missing interpolator” warning individually with `-Xlint:_,-missing-interpolator`
