### ISSUE TITLE
ES v3.2.0 compatibility

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore.JVM#41]
Hi @t3hnar 

I wonder if #619 mentioned in https://geteventstore.com/blog/20150906/event-store-3.2.0-released/index.html would cause any issues using the jvm client? It states the following:

*A new NotReady response to client API requests which are received before the server is ready (e.g. authentication set up) is used.*

**Comment by ahjohannessen** [comment]
I suppose you have already taken that into account as I can see the following in `SubscriptionOperation` and `SimpleOperation` :)

```scala
      case Failure(NotHandled(NotReady)) => retry
```

**Comment by t3hnar** [comment]
:)

But truly saying I have not tested with exactly `3.2.0` build yet.
Btw, I'm working right now on having JVM client with competing consumers support released.

**Comment by ahjohannessen** [comment]
Nice to hear :+1: It is going to be great to get a release that has that and 2.4 support :) Looking forward to it :sunglasses:

**Comment by gregoryyoung** [comment]
Not ready has been around for quite a while (about a year IIRC)

@t3hnar let me know if I can help with anything with competing.
