### ISSUE TITLE
EventStore.JVM example?

### ISSUE THREAD

**Issue by jansoren** [EventStore/EventStore.JVM#47]
Is there a good EventStore.JVM example out there?
Different implementations of event sourcing is using different naming (for example - projection is the same as query and view) 
Is there an architecture picture that shows which naming EventStore.JVM is using and is the naming reflected in the code?

**Comment by gregoryyoung** [comment]
None of those terms exist in the JVM client. There is a catchup
subscription which can be used for such things but it isn't an event
sourcing framework it only supports operations to the db

On Fri, Dec 11, 2015 at 11:21 AM, Jan-Terje Sørensen <
notifications@github.com> wrote:

> Is there a good EventStore.JVM example out there?
> Different implementations of event sourcing is using different naming (for
> example - projection is the same as query and view)
> Is there an architecture picture that shows which naming EventStore.JVM is
> using and is the naming reflected in the code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.JVM/issues/47>.
>



-- 
Studying for the Turing test

**Comment by jansoren** [comment]
Do you happen to know if there is someone who works with an Event Sourced framework for the EventStore.JVM? Or is it intended that EventStore.JVM is to become such a framework?

**Comment by gregoryyoung** [comment]
It is not intended to be a framework. As a product we prefer to not be
involved in operating frameworks and prefer there to many open opinionated
frameworks. This is also supported by many people who use eventstore not
actually using event sourcing at all but instead are using it as a
transport. That said there are a few on the JVM including axon and
akka.persistence. We do provide an adapter for the latter for axon it
should be a trivial exercise to add support for eventstore if its not
already there.

Greg

On Fri, Dec 11, 2015 at 4:00 PM, Jan-Terje Sørensen <
notifications@github.com> wrote:

> Do you happen to know if there is someone who works with an Event Sourced
> framework for the EventStore.JVM? Or is it intended that EventStore.JVM is
> to become such a framework?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.JVM/issues/47#issuecomment-163974339>
> .
>



-- 
Studying for the Turing test

**Comment by jansoren** [comment]
Thanks for the clarification :-)
