### ISSUE TITLE
Anonymous actors should be avoided if possible

### ISSUE THREAD

**Issue by pawelkaczor** [EventStore/EventStore.JVM#48]
While monitoring my app using the Kamon I got confused by names of anonymous actors showing up on the dashboard. The actors were constantly processing some messages. By examining the log I discovered that the actors were created by the Eventstore.JVM:

~~~
DEBUG akka://sales/user/$a/$a - started (eventstore.pipeline.TcpPipelineHandler@1f5502f7)
DEBUG akka://sales/user/$a/$a - now watched by Actor[akka://sales/user/$a#-1191817804]
DEBUG akka://sales/system/IO-TCP/selectors/$a/1 - now watched by Actor[akka://sales/user/$a#-1191817804]
DEBUG akka://sales/system/IO-TCP/selectors/$a/1 - now watched by Actor[akka://sales/user/$a/$a#1665270900]
DEBUG akka://sales/user - now supervising Actor[akka://sales/user/$b#-1183869946]
DEBUG akka://sales/user/$a/$a - now watched by Actor[akka://sales/system/IO-TCP/selectors/$a/1#1171102288]
DEBUG akka://sales/user/$b - started (eventstore.StreamPublisher@cf7dbde)
DEBUG akka://sales/user/$b - now watched by Actor[akka://sales/user/$a#-1191817804]
DEBUG akka://sales/user/$b - no longer watched by Actor[akka://sales/user/$a#-1191817804]
DEBUG akka://sales/user/$b - now watched by Actor[akka://sales/user/$a#-1191817804]
~~~

Is it possible to give some names to these actors?

**Comment by t3hnar** [comment]
@pawelkaczor not sure about names, but at least I can try to put them under a kind of supervisor

**Comment by pawelkaczor** [comment]
@t3hnar That would be nice. My goal is to filter them out using kamon metric filters.

**Comment by t3hnar** [comment]
@pawelkaczor do you still have issues with this?

**Comment by pawelkaczor** [comment]
Personally, at the moment, no. It is not urgent, for sure.

**Comment by t3hnar** [comment]
@pawelkaczor I double checked the code and basically there are possible solutions to separate actors created by eventstore. For example you can pass custom `ActorRefFactory`

Feel free to reopen in case you found something really blocking you.
