### ISSUE TITLE
Position of written event is always zero

### ISSUE THREAD

**Issue by rickardoberg** [EventStore/EventStore.JVM#51]
EventStore v3.5.0
Akka Client v2.2.1

When writing events using "ask(connection, message, writeTimeout)", but not immediately joining on the returned Future, I often get that the WriteEventsCompleted message always has the same range and position:
Some(EventNumber.Range(0 to 3)), position: Some(Position(0))

Isn't position supposed to increase every time an event is written?

The client in this case is doing a data import, but I limit it to 100 outstanding Futures (i.e. even if there is no join on the Future there can only be max 100 Futures that are not yet completed, if that helps at all).

**Comment by rickardoberg** [comment]
I have now verified that it is actually the exact same WriteEventsCompleted message object that is being handed to future.onComplete, over and over again. Hence the same position over and over again. In what circumstance would this happen?

**Comment by t3hnar** [comment]
Hi @rickardoberg , I have a feeling that you stored future of your first call and then reuses it by `joining` multiple times hence you are getting the same result. Once future completed - it does not change.
You need to use future of every `ask` separately.

**Comment by rickardoberg** [comment]
Hi @t3hnar, interesting theory. I added a debug output to onComplete to see if this was the case. Here's the output from two consecutive onComplete:
Some(EventNumber.Range(0 to 3)), position: Some(Position(0)), hash: 200448379, future: 2090793093, this: 37530582

Some(EventNumber.Range(0 to 3)), position: Some(Position(0)), hash: 200448379, future: 1812325936, this: 995644430

So, same WriteEventsCompleted object ("hash"), different futures (different hash values), and different anonymous inner class instances as handlers for onComplete. It seems indeed like the same WriteEventsCompleted message is being reused for different futures, which feels like a pretty serious bug. Is there anything else you want me to test? How could this happen?

Note that I don't always get this. On my local machine it's usually fine (not always though), but on my EC2 instances it always fails.

**Comment by t3hnar** [comment]
@rickardoberg  could you make a short prototype to reproduce your issue and paste it here?

**Comment by rickardoberg** [comment]
Here's a minimal repro test. Wrap it in a JUnit test to run (I made it invokable from my app to test it in EC2). If I run it locally it is fine, but in EC2 (with 3 instance cluster), I get the following output:

```
range: Some(EventNumber.Range(0 to 0)), position: Some(Position(0)), hash: -534031744, future: 1924958308, this: 2083016695
range: Some(EventNumber.Range(1 to 1)), position: Some(Position(0)), hash: 867522132, future: 1124383063, this: 75112552
range: Some(EventNumber.Range(2 to 2)), position: Some(Position(0)), hash: 355051107, future: 1493494578, this: 1472400994
```
[WriteTest.java.zip](https://github.com/EventStore/EventStore.JVM/files/204112/WriteTest.java.zip)

In this case the message, future, and handler seem to be different every time, with the main issue being that position is always zero. This is not what I'm seeing in my real app though, where the event is always the same. I'll see if I can reproduce that somehow. But to begin with, why is position zero? After write is completed I should be given the position. Otherwise... very bad.

**Comment by t3hnar** [comment]
@rickardoberg so according to your example, you are writing events to different streams, thus you have same range.

**Comment by rickardoberg** [comment]
@t3hnar not sure I follow. Yes, all events go to different streams (aggregate id's). But position is global right? Not per stream? As above, I only have a problem with this in EC2, locally it works as expected (position always increases).

**Comment by t3hnar** [comment]
@rickardoberg can you observer see zero position without cluster setup ?

**Comment by t3hnar** [comment]
So to clarify 

> When writing events using "ask(connection, message, writeTimeout)", but not immediately joining on the returned Future, I often get that the WriteEventsCompleted message always has the same range and position:

* same range - _is expected behaviour_
* same position - _unexpected_

And it has nothing todo with _when_ you are joining the `Future`


@gregoryyoung AFAIK client simply use Position received from server

**Comment by gregoryyoung** [comment]
@rickardoberg position there is referring to the position within the stream (if you do a second write it will be 1). We have considered also returning here the overall position (like the one used in a fromall subscription). Do you have a use case for needing it?

**Comment by rickardoberg** [comment]
@gregoryyoung oh, if that is the case I am really screwed, and also really confused. So, when I do a write I take the position and let the client know this, and next read is blocking until db updater has seen at least that position. If position is increasing globally for each write, it works, and locally that seems to be fine. Since the whole system is eventually consistent I am absolutely dependent on that position being increasing, or else I have no idea how long to block clients who wants to read state.

I have only seen this "position is within stream", i.e. zero most of the time on import, in the cluster. Same import locally, without cluster, and on EC2 with cluster turned off, produces continuously incrementing positions

**Comment by rickardoberg** [comment]
@t3hnar I can confirm that if I turn off cluster feature in EC2 and run import, then position increases properly as expected, and the object hash of each message is different.

**Comment by gregoryyoung** [comment]
@t3hnar which message?

https://github.com/EventStore/EventStore/blob/release-v3.6.0/src/Protos/ClientAPI/ClientMessageDtos.proto#L56

Here there is the first_event/last_event which will point to relative positions.

The prepare_position/commit_position should point to the log position (scratch my comment above about adding it was added).

Whether its single node or with a cluster should have no affect on this. 

If they are not can you provide me a repro?

**Comment by t3hnar** [comment]
@gregoryyoung 

Position.toString
```scala
override def toString =
      if (commitPosition == preparePosition) s"Position($commitPosition)"
      else s"Position($commitPosition,$preparePosition)"
```

**Comment by rickardoberg** [comment]
@gregoryyoung to add to my usecase: in the running system I use it as per above, for handling the eventual consistency. For the import I run several CSV imports in parallel, record the highest position of all WriteEventsCompleted, and afterwards just wait for db updater to have seen that highest position. In non-cluster this works great, but with cluster it doesn't work at all, as db updater reports commit position, and the WriteEventsCompleted always returns 0 as position, and so it all hangs. And since db updater uses commit position I'm guessing that not even switching to using a single stream for the whole app will make a difference, as that is a logical position being reported by WriteEventsCompleted, rather than log position, and so I would be comparing to different things.

In effect, this becomes a blocker for me being able to use EventStore clusters, it seems. It is absolutely crucial that the writer can get commit log position, rather than just logical position. And in non-cluster case it does, but in cluster it does not. The WriteTest zip in my previous comment should be enough to test this.

**Comment by gregoryyoung** [comment]
@rickardoberg it should be there.

You are saying you get it on a single node but not a cluster?

**Comment by t3hnar** [comment]
@gregoryyoung I've just tried with `ES 3.0.4.0` and it does work correctly for cluster. 
Going to try against `ES 3.5.0`

**Comment by rickardoberg** [comment]
@gregoryyoung for single node the WriteEventsCompleted returns commit position (=good), whereas in a cluster it returns stream position (=bad).

**Comment by gregoryyoung** [comment]
@rickardoberg it returns both on every message. I am a bit confused.https://github.com/EventStore/EventStore/blob/release-v3.6.0/src/Protos/ClientAPI/ClientMessageDtos.proto#L56

**Comment by t3hnar** [comment]
@rickardoberg @gregoryyoung cannot reproduce locally against cluster of 3 nodes `v3.5.0`

**Comment by t3hnar** [comment]
@gregoryyoung most probably not a client issue...

**Comment by rickardoberg** [comment]
@t3hnar are you saying that with the provided test case the position you get from WriteEventsCompleted is the commit position? Or what results exactly are you seeing?

**Comment by rickardoberg** [comment]
FFS, just saw that WriteTest does completed.position() instead of completed.position().get().commitPosition(). Going to see if that is what has been tripping me up all this while. BRB

**Comment by rickardoberg** [comment]
Nope, didn't help. If I run WriteTest against a single node it works, in that WriteEventsCompleted returns a commitPosition that increases. Same code against a 3-instance 3.5.0.0 EventStore cluster, and commitPosition is always 0, with the object hash of WriteEventsCompleted always being the same number (indicating the same instance being used). Any ideas are most welcome.

**Comment by t3hnar** [comment]
@rickardoberg looks like server issue.

> @t3hnar are you saying that with the provided test case the position you get from WriteEventsCompleted is the commit position? Or what results exactly are you seeing?

Exactly with your example it works as expected on my local OSX environment.

**Comment by gregoryyoung** [comment]
@t3hnar this entire thread is very confusing.

How are we determining that this is a server issue? If it is why can't you reproduce it?

**Comment by t3hnar** [comment]
@gregoryyoung as far as I can see client does not do magic inside and just proxies numbers received from server. Also there has been used same client on @rickardoberg side for both cluster and non-cluster setups, thus I assume that it is a server issue, do you personally suspect client? :)

**Comment by gregoryyoung** [comment]
I just want to nail down a reproduction :smile:

I have a suspicion of what could be a server issue but need to have a repro first. @rickardoberg can you confirm if the client is connected to the master node of the cluster or a slave?

**Comment by rickardoberg** [comment]
@gregoryyoung good catch! If I run the test on a server that connects to a slave, that is when I get the position=0. If I run the exact same test on a server that connects to master, then position increases as expected. So, it seems like writes to slaves are what is the problem. @t3hnar can you repro this with the code I gave you?

**Comment by gregoryyoung** [comment]
@rickardoberg my guess is the fields arent being copied after the forward->response. I will have to dig through for where that occurs

**Comment by gregoryyoung** [comment]
found it I will have a PR within 30-60 minutes

**Comment by rickardoberg** [comment]
Fantastic! Any sense of when the next maint release will be which includes this?

**Comment by gregoryyoung** [comment]
Its just about to begin testing. To be fair that branch is usually pretty stable. There are not that many changes in it as of now.

**Comment by gregoryyoung** [comment]
forgot to put earlier https://github.com/EventStore/EventStore/pull/883 you should be able to just build locally to test etc
