### ISSUE TITLE
Support for competing consumers

### ISSUE THREAD

**Issue by SoftMemes** [EventStore/EventStore.JVM#52]
I've started looking at the new competing consumers / persistent subscriptions available in EventStore, but cannot find any sign of them in this JVM client. I'd love to be able to use them but will need to do so from Java - is there a plan/timeline for support?

Connecting to a subscription group and ack/nak would be enough for my project atm, creating subscription groups could be done separately.

**Comment by gregoryyoung** [comment]
See https://github.com/EventStore/EventStore.JVM/tree/competing-consumers not sure of the state of it though @t3hnar ?

**Comment by michielboekhoff** [comment]
Hi there,

I'd really love to see this feature be supported. To that end, if no one is working on this, I'd be willing to see if I can't write something and create a PR for it at some point during the week?

**Comment by t3hnar** [comment]
hi @michielboekhoff I don't have enough time to finish adding this feature right now. 
There is branch to start off `competing-consumers`

**Comment by michielboekhoff** [comment]
@t3hnar Thanks for the quick response. I'll try and pick it up then.

**Comment by michielboekhoff** [comment]
@t3hnar Hi there. Right now I'm implementing Ack/NAck and I'm running into an issue: in the ConnectionActor's onPackOut function, it expects every packet to have an operation mapped in the Operation object. If the operation object is None, then the packet is not sent. I need a quick fire-and-forget solution to send the ack for a particular message. Any idea how to do that without rewriting part of the ConnectionActor?

**Comment by t3hnar** [comment]
@michielboekhoff I suppose that should be an ID of operation covering a whole competing consumer subscription, something like `SubscriptionOperation`. Does that make sense ?

**Comment by michielboekhoff** [comment]
This should be fixed by #74. We'll see a release with it soon, I imagine.

**Comment by michielboekhoff** [comment]
@t3hnar I've just built & published to a personal Nexus repository. I tested the client's PersistentSubscriptionActor and it works, except for one thing. Even though the test for an ack being sent to the connection passes, the connection seemingly does not pass it onto the server. Any idea what could be causing this?

**Comment by michielboekhoff** [comment]
This should be closed now - #74 has been merged.
