### ISSUE TITLE
Require master flag taken from Default settings rather than connection settings

### ISSUE THREAD

**Issue by kristian-elder** [EventStore/EventStore.JVM#54]
WriteEvents in Message.scala uses Settings.Default.requireMaster as default value for requireMaster and EsConnectionImpl does not pass an override.

For now we can work around this by using the config files, but as we have another config system in place, we'd really prefer that the setting from the Settings object passed to EsConnectionFactory.create would be used (as expected).

This appears to affect all operations, not just writes.

**Comment by gregoryyoung** [comment]
You can specify as well reads to require master (and there are some reasons you may prefer to do this)

**Comment by kristian-elder** [comment]
Not objecting to that statement at all, for us this simply came up in a write.

The issue is that you cannot specify in code whether to require master or not, per connection or per operation - the setting from external configuration is always used.

**Comment by t3hnar** [comment]
@kristian-elder But EsConnection is not supposed override this, you should pass on per message basis like `WriteEvents(requireMaster = true)`

**Comment by kristian-elder** [comment]
Sorry, I should have been more precise.

This is for the Java API: eventstore.j.EsConnection

**Comment by t3hnar** [comment]
@kristian-elder I will add ability to pass `requireMaster` as argument to `EsConnection.writeEvents` method

**Comment by t3hnar** [comment]
And also use connection settings in case `requireMaster` is not passed via method

**Comment by kristian-elder** [comment]
Awesome, many thanks!

**Comment by t3hnar** [comment]
Fixed in [v2.2.2](http://search.maven.org/#search%7Cga%7C1%7Cg%3Acom.geteventstore%20AND%20eventstore-client)
