### ISSUE TITLE
LinkTo functionality

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore.JVM#57]
Would it be possible to get some sort of LinkTo functionality similar to that you have in JS projections? I rather stay away from JS code, and thought that it could be a nice feature to have, if possible. Essentially doing the filtering on client side and avoiding duplicate space by using links.

@gregoryyoung Is LinkTo possible via ES API?

**Comment by jen20** [comment]
You can - look at the event format which is created by a linkTo and replicate it with your own write.

I believe the event type has to be `$>` and the body must be of the form `streamName@eventNumber`.

**Comment by ahjohannessen** [comment]
@jen20 Great, that sounds promising :)

**Comment by jen20** [comment]
Great - I'll close this issue for now - please feel free to reopen if you have difficulties writing the links!

**Comment by ahjohannessen** [comment]
@jen20 I was more thinking that it could be a nice feature to add to the JVM client, but perhaps first kick some tires before suggesting that it should be a part of the JVM client.

**Comment by gregoryyoung** [comment]
What would be the 'feature'? Its just an event with a type name

On Fri, Jul 8, 2016 at 2:09 PM, Alex Henning Johannessen <
notifications@github.com> wrote:

> @jen20 <https://github.com/jen20> I was more thinking that it could be a
> nice feature to add to the JVM client, but perhaps first kick some tires
> before suggesting that it should be a part of the JVM client.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/EventStore/EventStore.JVM/issues/57#issuecomment-231334579>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXRWg4ihbcQ_RcH2xRn0ZQ2Kl1fyMUhks5qTi_2gaJpZM4JH7Cz>
> .
>



-- 
Studying for the Turing test

**Comment by ahjohannessen** [comment]
@gregoryyoung Ability to have that functionality and let the JVM client worry about potential gotchas and details wrt. type has to be `$>` and body must be of form `streamName@eventNumber`. However, it was mostly an idea that I thought could be very useful for our applications and did not know what it would take to make that happen. 

Sure, I will try make this myself first. Is there anything special to have in mind, like idempotency or similar?

**Comment by t3hnar** [comment]
There is such feature in JVM client, https://github.com/EventStore/EventStore.JVM/blob/master/src/main/scala/eventstore/Event.scala#L19

**Comment by t3hnar** [comment]
there are some tests covering `LinkTo` functionality you can use as examples
https://github.com/EventStore/EventStore.JVM/blob/master/src/test/scala/eventstore/TestConnection.scala#L57

**Comment by ahjohannessen** [comment]
Look how enlightened I am :dancers: - Super @t3hnar
