### ISSUE TITLE
Upgrade protobuf to 3.0.0

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore.JVM#61]
Is there a chance that we can upgrade protobuf to 3.0.0 or perhaps rely on akka-protobuf instead (which I believe is 2.5.0 internalized to akka)?

Protobuf 3.0.0 should be able to handle proto2 formats just fine.

**Comment by t3hnar** [comment]
I'll check

**Comment by ahjohannessen** [comment]
Great :) Also, the following projects might be of interest with regards to having a protoc jar instead of fetching native bits in your CI build file:
 - https://github.com/os72/protoc-jar 
 - https://github.com/sbt/sbt-protobuf

**Comment by t3hnar** [comment]
thx, proton-jar is a nice finding

**Comment by t3hnar** [comment]
@ahjohannessen as far as I can see akka still uses protobuf version `2.4.9`

**Comment by t3hnar** [comment]
@ahjohannessen upgrade to 3.0.0 won't happen for now... Also I cannot externalise to akka's protobuf version as client does not require corresponding akka modules.

What's your use case which raised this issue?

**Comment by ahjohannessen** [comment]
As far as I can tell by browsing dependencies on https://index.scala-lang.org/akka/akka I do not see any google protobuf dependency.

The use case that raises this is using gprc 1.0.0 in projects that use eventstore-jvm and persistence.

**Comment by t3hnar** [comment]
@ahjohannessen oh what a confusion... 
http://repo1.maven.org/maven2/com/typesafe/akka/akka-remote_2.11/2.4.9/akka-remote_2.11-2.4.9.pom
it's `akka-protobuf`

**Comment by ahjohannessen** [comment]
Yes, akka-protobuf is a copy and paste of protobuf 2.5.0, IIRC - done in order to avoid situations like this one.

**Comment by t3hnar** [comment]
@ahjohannessen Yep, I can see this now, was not like this when I added deps.

**Comment by ahjohannessen** [comment]
This was the commit that introduced akka-protobuf: https://github.com/akka/akka/commit/c3ecb87a65b807ce304b40b946baae525ce5158b

**Comment by ahjohannessen** [comment]
It might be an idea to go with akka-protobuf in order to sidestep dependency conflicts.

**Comment by t3hnar** [comment]
most probably

**Comment by ahjohannessen** [comment]
@t3hnar I think you need to specify that your protobuf definitions should use `syntax = "proto2";` at the top of the file such that protoc does not complain about `required` fields etc.

Btw, thanks for doing this 👍

**Comment by ahjohannessen** [comment]
@t3hnar For the record, this is an interesting trick:
```scala
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("com.google.protobuf.**" -> "shadeproto.@1").inAll
)
```
one can do with this plugin:
```scala
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.2")
```
ScalaPB does that with respect to SparkSQL.

**Comment by t3hnar** [comment]
@ahjohannessen you know pull requests are welcome :)

**Comment by ahjohannessen** [comment]
@t3hnar Yes ;)
