### ISSUE TITLE
Issue when trying to fetch the metadata of a stream that has one event

### ISSUE THREAD

**Issue by fchaillou** [EventStore/EventStore.JVM#63]
Hello,

When i try to get the stream metadata of a stream that has events and no metadata, i get a weird exception.

Here is a test case to reproduce : https://gist.github.com/fchaillou/453fe7ab621870c78c921c4523f84135

When running it i get `Exception in thread "main" eventstore.CommandNotExpectedException: Expected: ReadEventCompleted, actual: java.lang.IllegalArgumentException: requirement failed: streamId must not be empty`

Thanks !

**Comment by t3hnar** [comment]
@fchaillou thx, interesting one, will take a look
