### ISSUE TITLE
Values given by operation.timeout configuration and SettingsBuilder.operationTimeout() are ignored 

### ISSUE THREAD

**Issue by Konfuzzyus** [EventStore/EventStore.JVM#66]
Observed behavior:
Setting an operationTimeout <> 7s using the SettingsBuilder or the configuration file does not change the timeout used for akka ask operations. The timeout actually used is always the default timeout (as specified in the Settings class).

Expected behavior:
Setting the operationTimeout to 15s should also make akka ask operations use a timeout of 15s.

Root cause analysis:
The SettingsBuilder class omits to fill in the operationTimeout attribute of the Settings object it builds:

```
  def build: Settings = Settings(
    address = _address,
    maxReconnections = _maxReconnections,
    reconnectionDelayMin = _reconnectionDelayMin,
    reconnectionDelayMax = _reconnectionDelayMax,
    defaultCredentials = _defaultCredentials,
    heartbeatInterval = _heartbeatInterval,
    heartbeatTimeout = _heartbeatTimeout,
    operationMaxRetries = _operationMaxRetries,
    // TODO: missing:
    // operationTimeout = _operationTimeout,
    connectionTimeout = _connectionTimeout,
    resolveLinkTos = _resolveLinkTos,
    requireMaster = _requireMaster,
    readBatchSize = _readBatchSize,
    bufferSize = _bufferSize,
    cluster = _cluster)
```

**Comment by t3hnar** [comment]
Thx for reporting!

**Comment by Konfuzzyus** [comment]
Verified to be working using release 2.4.0.

+1
