### ISSUE TITLE
Usage of com.typesafe.play play-json 2.5.4 introduces dependency on logback-classic

### ISSUE THREAD

**Issue by Konfuzzyus** [EventStore/EventStore.JVM#67]
Observed Behavior:
Eventstore.JVM v2.4.0 adds a dependency on the logback-classic slf4j-binding and breaks setups that deploy using other slf4j-bindings.

Expected Behavior:
Eventstore.JVM should not introduce any dependencies on specific slf4j-bindings.

Root Cause Analysis:
Version 2.5.4 of play-json is affected by https://github.com/playframework/playframework/issues/6242 which leaks its test dependency on logback into the release package. Please update to version 2.5.5 or greater at the next opportunity. We are currently working around the problem by blocking the dependency.

**Comment by t3hnar** [comment]
Thx, will do!
