### ISSUE TITLE
Streaming from First element on a stream that has been soft-deleted returns different elements depending on infinite

### ISSUE THREAD

**Issue by samidalouche** [EventStore/EventStore.JVM#69]
`stream_that_has_been_soft_deleted` contains `3311` elements starting from offset `33338`

The following code will return 0 if infinite = false, and will return 50 if infinite = true.

Is that the expected behavior? What is the preferred/correct way of asking for the first element, whatever the offset is?

```scala
val publisher = omrunModule.connection.streamPublisher(
    streamId = EventStream.Id("stream_that_has_been_soft_deleted"),
    fromNumberExclusive = Some(EventNumber.First),
    infinite = false
  )
val systemTerminated = Source
    .fromPublisher(publisher)
    .map(esEvent => Event(esEvent))
//    .filter(x => predicate(x._2))
      .take(50)
      .fold(0) { case (x, v) => x + 1}
    .runForeach { result =>
      println(result)
    }
    .flatMap { _ =>
      system.terminate()
    }

  Await.result(systemTerminated, Duration.Inf)
```

**Comment by t3hnar** [comment]
Your code looks valid to me, so probably some kind of issue... will try to fix it.
As temporary workaround try to `fromNumberExclusive=None`

Btw with so small `take = 50` you can just send single `ReadEvents` like described here https://github.com/EventStore/EventStore.JVM#future-like-api

**Comment by samidalouche** [comment]
The take(50) was only added for trying to debug the finite/infinite case. None works the same as `EventNumber.First`, which does the same as `Exact(X)` where `X` < firstElement - 500

**Comment by t3hnar** [comment]
@samidalouche there is a bug, thx for reporting.

Meanwhile you can workaround it like querying the offset first and then using it as `fromNumberExclusive`
You can query last event number by  sending msg `ReadEvent(stream, EventNumber.Last)`

**Comment by samidalouche** [comment]
Great, Thanks!
