### ISSUE TITLE
Update Scala version.

### ISSUE THREAD

**Issue by michielboekhoff** [EventStore/EventStore.JVM#73]
Hello,

Scala has recently (October 2016) released Scala 2.12. As a result, this library does not work with the newest release of Scala. Any plans to upgrade? Possibly, if no on else has time, I can take a look at doing this myself and creating a PR.

**Comment by t3hnar** [comment]
@michielboekhoff we rely on play-json dependency that blocks use from building against `2.12`

**Comment by michielboekhoff** [comment]
@t3hnar I've checked the roadmap for Play 2.6 and it's expected in March - April of this year. Maybe something lighter could be used, so that it's not blocking 2.12 until then? I'd be happy to pick this up myself sometime next week.

**Comment by t3hnar** [comment]
@michielboekhoff I'd not say that `play-json` is not light :)
you can take a look at https://github.com/circe/circe

**Comment by DStranger** [comment]
@michielboekhoff @t3hnar I am currently working on replacing `play-json` with `circe`, will create a PR tomorrow.

**Comment by michielboekhoff** [comment]
@DStranger Thanks, that'd be much appreciated. If you need any help please let me know.

**Comment by DStranger** [comment]
On the second thought, `circe` will bring a dependency on `cats`, what are your thought on that, @t3hnar? Another option would be `spray-json`, which is also lightweight enough.

**Comment by t3hnar** [comment]
@DStranger 
Adding dependency on `cats` is a bad idea.
I have a fear that `spray-json` may die because of other better supported and more powerful libraries.
So I still think that `play-json` is the best one option, but we can migrate temporary to other lib until `play-json` migrated to scala 2.11. In such case `spray-json` is the best choice.

**Comment by michielboekhoff** [comment]
I see that play-json has now been replaced. Can we now bump the Scala version, or is there anything else holding us back?

**Comment by t3hnar** [comment]
should be available on maven central under v3.0.6 in couple of hours
