### ISSUE TITLE
Release new version of EventStore.JVM on Maven.

### ISSUE THREAD

**Issue by michielboekhoff** [EventStore/EventStore.JVM#84]
Hey, 

I've contributed a number of PRs to this repository, one of which implements competing consumers. I was wondering when a new release will take place so we won't have to host `master` on our local Nexus.

Thanks.

**Comment by t3hnar** [comment]
hi @michielboekhoff thanks for your contributions, released under `4.0.0`

**Comment by michielboekhoff** [comment]
@t3hnar Thank you very much for the excellent code that underlies this repository!
