### ISSUE TITLE
Question about running in jUnit test (java)

### ISSUE THREAD

**Issue by Mousaka** [EventStore/EventStore.JVM#86]
I have set up a jUnit test that basically just runs the java example from the README of how to Write an event to EventStore.
I noticed that the test successfully creates and pushes events to my EventStore if I run the tests through maven (`mvn test`) but if I run them in my IDE (IntelliJ) no events are created and no errors are shown either. Any idea why that is? and what can I do to be able to run tests against EventStore from IntelliJ?

Cheers

**Comment by t3hnar** [comment]
@Mousaka can you see that tests are run at all?

**Comment by Mousaka** [comment]
Yes the test gets run. If I put a fail() at the end of it it fails for example.

**Comment by t3hnar** [comment]
Most of tests are unit, they do not use EventStore, however you can try to run for instance 
`ReadWriteEvents`
`ReadStreamEventsForwardITest`

**Comment by Mousaka** [comment]
Hi again and thanks for helping me
I cloned the EventStore.JVM project and tried running `ReadWriteEvents` and `ReadStreamEventsForwardITest` and I see them both interacting with my EventStore so they seem to work.
However the test `ReadStreamEventsForwardITest` [fails](https://gist.github.com/Mousaka/afeba283530de395e5c4287477e1cae9)  when I run the test it directly in IntelliJ (right click on file + Run test), but all tests succeed when I run tests through sbt. When the tests are failing I can still see them connecting to EventStore - this is different from my test where I don't see any interaction with EventStore (when not running them with maven).

**Comment by Mousaka** [comment]
So I got it to work now by using the "Future"-pattern that is recommended in the readme. My test can now communicate with EventStore even if I run it directly form my IDE. I am not so familiar with writing tests in an Akka-environment but my guess of why it wouldn't work for me is about the tasks being asynchronous and if you code it wrong jUnit will just finish before the event was sent or something. Still weird that my "bad code" worked with maven though. Here is the code that worked for me:
```java
   @Test
   public void writeEventTestMethod2() {
      final EventData event = new EventDataBuilder("event-type")
              .eventId(UUID.randomUUID())
              .jsonData("{\"name\": \"Waho\",\"ssn\": \"1912121212\"}")
              .metadata("my first event")
              .build();

      final ActorSystem system = ActorSystem.create();
      final EsConnection connection = EsConnectionFactory.create(system, settings);
      final Future<eventstore.WriteResult> future = connection.writeEvents("newstream", null, asList(event), credentials);

      future.onSuccess(new Success<>(), system.dispatcher());
      future.onFailure(new Failure<>(), system.dispatcher());
      final Timeout timeout = new Timeout(Duration.create(5, "seconds"));
      try {
         final eventstore.WriteResult result = Await.result(future, timeout.duration());
         System.out.println(result);
      } catch (Exception e) {
         e.printStackTrace();
         fail();
      }
   }
```
