### ISSUE TITLE
Unable to resubscribe when using streamPublisher and the connection drops for a short moment

### ISSUE THREAD

**Issue by sbmpost** [EventStore/EventStore.JVM#88]
When creating an Akka Source using the streamPublisher method in EsConnection, it returns an ActorPublisher. This works fine as long as the connection is up. If however for some reason the client connection is down for a few seconds (due to a network glitch) and later on the connection comes back up, the subscription is lost. As far as I can tell there is no way to detect this and to resubscribe (in contrast to EsConnection.subscribeToStream where you can use a SubscriptionObserver).

My current workaround is to set max-reconnections = 0 in the config and watching the ConnectionActor. When it terminates I do the reconnect and resubscribe 'manually'.

**Comment by sbmpost** [comment]
After some research I came up with the following analysis + a patch

commit e66e3d7cce810ea4ff30b90ac649195799e3dc68
Author: Stefan Post <s.post@thenewmotion.com>
Date:   Thu May 11 16:48:59 2017 +0200

    When reconnecting, the connect itself may succeed, but retrying the subscribeTo operation
    may timeout. This happens for example when EventStore is in the process of restarting. If
    we wouldn't have the timeout and subscribeTo indeed times out, we will never be informed
    about it and consequently can never recover from it.

diff --git a/src/main/scala/eventstore/tcp/ConnectionActor.scala b/src/main/scala/eventstore/tcp/ConnectionActor.scala
index b56387f..e274b56 100644
--- a/src/main/scala/eventstore/tcp/ConnectionActor.scala
+++ b/src/main/scala/eventstore/tcp/ConnectionActor.scala
@@ -281,6 +281,7 @@ private[eventstore] class ConnectionActor(settings: Settings) extends Actor with
       val result = os.flatMap { operation =>
         operation.connected match {
           case OnConnected.Retry(operation, packOut) =>
+            system.scheduler.scheduleOnce(settings.operationTimeout, self, TimedOut(packOut.correlationId, operation.version))
             connection(packOut)
             List(operation)
           case OnConnected.Stop(in) =>

**Comment by t3hnar** [comment]
Nice! @sbmpost could you please fire a pull request ?

**Comment by sbmpost** [comment]
PR: https://github.com/EventStore/EventStore.JVM/pull/89
The build seems to fail because of a permission issue...

**Comment by t3hnar** [comment]
fixed in `v4.1.1`

**Comment by sbmpost** [comment]
Nice, thanks :-)
