### ISSUE TITLE
How to setup competing consumers in scala?

### ISSUE THREAD

**Issue by evan108108** [EventStore/EventStore.JVM#93]
Hi all I am having trouble figuring out how I can setup "Persistent Subscription"'s in scala. Does anyone  have any sample code?

**Comment by evan108108** [comment]
Okay I don't know how I missed this. I am going to try this and close this issue.

https://github.com/EventStore/EventStore.JVM/blob/master/src/main/scala/eventstore/examples/PersistentSubscriptionExample.scala

**Comment by evan108108** [comment]
Re-opening because when I run the example linked above I get the following error message:

```bash
Event(Failure(eventstore.CommandNotExpectedException: Expected: Connected, actual: eventstore.SubscriptionDropped$NotFound$),ConnectionDetails)
```

If anyone has any insights on how I might solve this let me know. Thx...

**Comment by evan108108** [comment]
Okay I understand why it says "eventstore.SubscriptionDropped$NotFound$". I need to create the subscription first, however it is not apparent to me how to do this in Scala. Can someone help me with some sample code?

**Comment by t3hnar** [comment]
please try
```scala
val connection = EsConnection(system)
connection(PersistentSubscription.Create(streamId, groupName, settings))
```

**Comment by evan108108** [comment]
@t3hnar <- Thanks that worked!
