### ISSUE TITLE
Replace ActorPublisher with GraphStage.

### ISSUE THREAD

**Issue by michielboekhoff** [EventStore/EventStore.JVM#99]
Hi,

In my Scala build, I'm currently getting a deprecation warning:

`object ActorPublisher` in package actor is deprecated (since 2.5.0): Use `akka.stream.stage.GraphStage` instead, it allows for all operations an Actor would and is more type-safe as well as guaranteed to be ReactiveStreams compliant.

We should therefore replace the `ActorPublisher`s with `GraphStage`.

**Comment by t3hnar** [comment]
Pull requests are welcome :)

**Comment by evan108108** [comment]
@t3hnar any progress on this?
